data:
  raw: "../data/raw/creditcard.csv"
  processed: "../data/processed/creditcard-processed.csv"

models:
  classifiers:
    - Logistic Regression
    - KNearestClassifier
    - RandomForestClassifier
  
  anomaly_detector:
    - IsolationForest

preprocessing:
  sampling: "SMOTE"
  test_size: 0.2
  random_state: 42
  target_column: "Class"

output:
  model_dir: "models/"
  report_dir: "docs/technical_report.pdf"

knn_best_params:
  n_neighbors: 11
  p: 1
  weights: "distance"

rfs_best_params:
  class_weight: "balanced"
  max_depth: 20
  max_features: "sqrt"
  n_estimators: 299

lr_best_params:
  class_weight: "balanced"
  penalty: "l1"
  solver: "saga"

evaluation:
  metrics: ["precision", "recall", "accuracy", "roc_auc_score"]
